export const MOVIES_DATA = {
    "Featured": {
        "Id": "0",
        "Title": "The Irishman",
        "CoverImage": "FeaturedCoverImage.png",
        "TitleImage": "FeaturedTitleImage.png",
        "Date": "2021-10-24T12:16:50.894556",
        "ReleaseYear": "2021",
        "MpaRating": "18+",
        "Category": "Movie",
        "Duration": "6000",
        "VideoUrl": "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
        "Description": 'orem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.'
    },
    "TendingNow": [
        {
            "Id": "1",
            "Title": "Title 1",
            "CoverImage": "https_specials-1.png",
            "TitleImage": "FeaturedTitleImage.png",
            "Date": "2021-10-24T12:16:50.894556",
            "ReleaseYear": "2021",
            "MpaRating": "18+",
            "Category": "Movie",
            "Duration": "2000",
            "VideoUrl": "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
            "Description": "Info About it"
        },
        {
            "Id": "2",
            "Title": "Title 2",
            "CoverImage": "https_specials-2.png",
            "TitleImage": "FeaturedTitleImage.png",
            "Date": "2021-10-12T12:16:50.894556",
            "ReleaseYear": "2021",
            "MpaRating": "18+",
            "Category": "TV Show",
            "Duration": "2300",
            "VideoUrl": "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
            "Description": "t is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        },
        {
            "Id": "3",
            "Title": "Title 3",
            "CoverImage": "https_specials-3.png",
            "TitleImage": "FeaturedTitleImage.png",
            "Date": "2021-10-11T12:16:50.894556",
            "ReleaseYear": "2021",
            "MpaRating": "18+",
            "Category": "Movie",
            "Duration": "6000",
            "VideoUrl": "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
            "Description": "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum"
        },
        {
            "Id": "4",
            "Title": "Title 4",
            "CoverImage": "https_specials-4.png",
            "TitleImage": "FeaturedTitleImage.png",
            "Date": "2021-10-10T12:16:50.894556",
            "ReleaseYear": "2021",
            "MpaRating": "18+",
            "Category": "Movie",
            "Duration": "4000",
            "VideoUrl": "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
            "Description": "here are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful"
        },
        {
            "Id": "5",
            "Title": "Title 5",
            "CoverImage": "https_specials-5.png",
            "TitleImage": "FeaturedTitleImage.png",
            "Date": "2021-10-15T12:16:50.894556",
            "ReleaseYear": "2021",
            "MpaRating": "18+",
            "Category": "TV Show",
            "Duration": "5300",
            "VideoUrl": "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
            "Description": "Info About it"
        },
        {
            "Id": "6",
            "Title": "Title 6",
            "CoverImage": "https_specials-6.png",
            "TitleImage": "FeaturedTitleImage.png",
            "Date": "2021-10-22T12:16:50.894556",
            "ReleaseYear": "2021",
            "MpaRating": "18+",
            "Category": "TV Show",
            "Duration": "1200",
            "VideoUrl": "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
            "Description": "Info About it"
        },
        {
            "Id": "7",
            "Title": "Title 7",
            "CoverImage": "https_specials-7.png",
            "TitleImage": "FeaturedTitleImage.png",
            "Date": "2021-11-22T12:16:50.894556",
            "ReleaseYear": "2021",
            "MpaRating": "18+",
            "Category": "Movie",
            "Duration": "4500",
            "VideoUrl": "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
            "Description": "Info About it"
        },
        {
            "Id": "8",
            "Title": "Title 8",
            "CoverImage": "https_specials-8.png",
            "TitleImage": "FeaturedTitleImage.png",
            "Date": "2021-07-14T12:16:50.894556",
            "ReleaseYear": "2021",
            "MpaRating": "18+",
            "Category": "TV Show",
            "Duration": "2000",
            "VideoUrl": "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
            "Description": "Info About it"
        },
        {
            "Id": "9",
            "Title": "Title 9",
            "CoverImage": "https_specials-1.png",
            "TitleImage": "FeaturedTitleImage.png",
            "Date": "2021-04-03T12:16:50.894556",
            "ReleaseYear": "2021",
            "MpaRating": "18+",
            "Category": "Movie",
            "Duration": "2300",
            "VideoUrl": "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
            "Description": "Info About it"
        },
        {
            "Id": "10",
            "Title": "Title 10",
            "CoverImage": "https_specials-2.png",
            "TitleImage": "FeaturedTitleImage.png",
            "Date": "2021-11-23T12:16:50.894556",
            "ReleaseYear": "2021",
            "MpaRating": "18+",
            "Category": "Movie",
            "Duration": "6000",
            "VideoUrl": "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
            "Description": "Info About it"
        },
        {
            "Id": "11",
            "Title": "Title 11",
            "CoverImage": "https_specials-3.png",
            "TitleImage": "FeaturedTitleImage.png",
            "Date": "2021-11-04T12:16:50.894556",
            "ReleaseYear": "2021",
            "MpaRating": "18+",
            "Category": "TV Show",
            "Duration": "1200",
            "VideoUrl": "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
            "Description": "Info About it"
        },
        {
            "Id": "12",
            "Title": "Title 12",
            "CoverImage": "https_specials-4.png",
            "TitleImage": "FeaturedTitleImage.png",
            "Date": "2021-03-03T12:16:50.894556",
            "ReleaseYear": "2021",
            "MpaRating": "18+",
            "Category": "Movie",
            "Duration": "3400",
            "VideoUrl": "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
            "Description": "Info About it"
        },
        {
            "Id": "13",
            "Title": "Title 13",
            "CoverImage": "https_specials-5.png",
            "TitleImage": "FeaturedTitleImage.png",
            "Date": "2021-12-30T12:16:50.894556",
            "ReleaseYear": "2021",
            "MpaRating": "18+",
            "Category": "Movie",
            "Duration": "6500",
            "VideoUrl": "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
            "Description": "Info About it"
        },
        {
            "Id": "14",
            "Title": "Title 14",
            "CoverImage": "https_specials-6.png",
            "TitleImage": "FeaturedTitleImage.png",
            "Date": "2021-07-10T12:16:50.894556",
            "ReleaseYear": "2021",
            "MpaRating": "18+",
            "Category": "Movie",
            "Duration": "5000",
            "VideoUrl": "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
            "Description": "Info About it"
        },
        {
            "Id": "15",
            "Title": "Title 15",
            "CoverImage": "https_specials-7.png",
            "TitleImage": "FeaturedTitleImage.png",
            "Date": "2021-05-14T12:16:50.894556",
            "ReleaseYear": "2021",
            "MpaRating": "18+",
            "Category": "Movie",
            "Duration": "1300",
            "VideoUrl": "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
            "Description": "Info About it"
        },
        {
            "Id": "16",
            "Title": "Title 16",
            "CoverImage": "https_specials-8.png",
            "TitleImage": "FeaturedTitleImage.png",
            "Date": "2021-03-25T12:16:50.894556",
            "ReleaseYear": "2021",
            "MpaRating": "18+",
            "Category": "Movie",
            "Duration": "5000",
            "VideoUrl": "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
            "Description": "Info About it"
        },
        {
            "Id": "17",
            "Title": "Title 17",
            "CoverImage": "https_specials-1.png",
            "TitleImage": "FeaturedTitleImage.png",
            "Date": "2021-08-24T12:16:50.894556",
            "ReleaseYear": "2021",
            "MpaRating": "18+",
            "Category": "TV Show",
            "Duration": "400",
            "VideoUrl": "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
            "Description": "Info About it"
        },
        {
            "Id": "18",
            "Title": "Title 18",
            "CoverImage": "https_specials-2.png",
            "TitleImage": "FeaturedTitleImage.png",
            "Date": "2021-07-21T12:16:50.894556",
            "ReleaseYear": "2021",
            "MpaRating": "18+",
            "Category": "TV Show",
            "Duration": "1200",
            "VideoUrl": "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
            "Description": "Info About it"
        }
    ]
};
